In [1]:
import numpy as np

In [9]:
## array(): it creates array from list or tuples. SYNTAX=array(object,dtype=None,copy=True,order='k') ##

a=np.array([1,2],'complex')
print(a)

a=np.array([1,2],'float')
print(a)

b=np.array([[1,2],[3,4]])
print(b)

a=np.array([[1,2],[3,4]],order='c')
print(a)

[1.+0.j 2.+0.j]
[1. 2.]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [11]:
#ARANGE CREATES ARRAY OF EVENLY SPACED VALUES :arange(start,stop,step,dtype=None) ##
 ## start is optional default 0 ,sto is compulsory ##

In [12]:
a=np.arange(3.0,20)
b=np.arange(20,dtype='complex')
print(a)
print(b)

[ 3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j
  9.+0.j 10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j 16.+0.j 17.+0.j
 18.+0.j 19.+0.j]


In [13]:
#zeros : it creates array filled with zeros ##
## zeros(shape,dtype=float,order='c') ## c is for rows, k for columns

In [15]:
b=np.zeros(5)
print(b)

a=np.zeros((2,3),dtype="complex")
print(a)

[0. 0. 0. 0. 0.]
[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [18]:
# ones  it creates array filled with 1's #
## syntax: ones(shape,dtype=None,order='c') by default datatype is float ##

In [19]:
a=np.ones((2,3))
b=np.ones(7,dtype='int')
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[1 1 1 1 1 1 1]


In [20]:
#linspace :it divides array into evenly spaced values ,same like arange but here we have to specify no of breakpoints ##
## syntax: linspace(start,stop,num=50,endpoint=True)  by default num is 50 and endpoint is true ##

In [24]:
a=np.linspace(2.0,4.0)
print(a)

a=np.linspace(2,8,num=4)
print(a)

a=np.linspace(2,8,num=4,endpoint=False)
print(a)

[2.         2.04081633 2.08163265 2.12244898 2.16326531 2.20408163
 2.24489796 2.28571429 2.32653061 2.36734694 2.40816327 2.44897959
 2.48979592 2.53061224 2.57142857 2.6122449  2.65306122 2.69387755
 2.73469388 2.7755102  2.81632653 2.85714286 2.89795918 2.93877551
 2.97959184 3.02040816 3.06122449 3.10204082 3.14285714 3.18367347
 3.2244898  3.26530612 3.30612245 3.34693878 3.3877551  3.42857143
 3.46938776 3.51020408 3.55102041 3.59183673 3.63265306 3.67346939
 3.71428571 3.75510204 3.79591837 3.83673469 3.87755102 3.91836735
 3.95918367 4.        ]
[2. 4. 6. 8.]
[2.  3.5 5.  6.5]


In [25]:
### EYE :it returns array filled with zeros except in kth diagonal whose values are equal to 1 ##
 ## syntax: eye(n,m=None,k=0,dtpe='int') n=rows,m=columns (optional) ##
    ##  k=0 by default for  k=1 upper diagonal, for k=-1 lower diagonal ##

In [27]:
a=np.eye(3,3)
print(a)

a=np.eye(3,3,k=1)
print(a)

a=np.eye(3,k=-1)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [28]:
## random ##
## rand: random float values ##
## randint: random integer ##
## choice :random value from given list ##
## size will specify the shape of an array ##

In [44]:
from numpy import random

a= random.rand(10) 
print(a)


a= random.randint(10) 
print(a)
a= random.randint(10,size=(3,3))
print(a)


a = random.choice([3, 5, 7, 9])
print(a)

[0.47720744 0.36254982 0.33274832 0.08447933 0.78695803 0.25687333
 0.60340935 0.67720801 0.78332697 0.48042195]
5
[[2 3 7]
 [3 8 3]
 [5 7 2]]
3


In [ ]:
### Attributes ##

In [47]:
a=np.array([[1,2,3],[3,4,5]])
print(a.shape)  ## to find shape of array ##
print(a.ndim) ## to find dimension of array ##

(2, 3)
2


In [48]:
a.dtype  ## to find data type of array ##

dtype('int32')

In [49]:
a.itemsize ## to find size of each item in bytes ##

4

In [50]:
a.size   ## to find no of elements in array ##

6

In [ ]:
### INDEXING ## index starts from 0 to n-1
## 1d array:a[i] 2d array:a[i][j]##

In [60]:
a=np.arange(1,10)
print(a)
print(a[2])

a=np.arange(1,10).reshape(3,3)
print(a)
print(a[2][1])

[1 2 3 4 5 6 7 8 9]
3
[[1 2 3]
 [4 5 6]
 [7 8 9]]
8


In [68]:
## boolean indexing ## 
a=np.arange(1,10)
print(a[a<4]) ## accesing values less than 4 ##
print(a[a%2==0])  ## accesing even values in array##

[1 2 3]
[2 4 6 8]


In [69]:
## ARITHMETIC OPERATIONS ##
a=np.arange(1,5)
print(a)
print(a+2) ## adding 2 to every element in array ##

[1 2 3 4]
[3 4 5 6]


In [71]:
print(a*2)  ## multiplying with 2 to every element in array ##

[2 4 6 8]


In [ ]:
## ARRAY MANIPULATIONS ##

In [72]:
## reshape ## no of elements in array should be equal to shape i.e mxn=size
a=np.arange(1,7).reshape(2,3)
b=np.arange(7,13).reshape(3,2)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [76]:
## RESIZE: resize(oldarray,shape) if new array is larger than old array then it will repeat elements in old array ##

a=np.arange(1,10)
print(a)

b=np.resize(a,(4,3))
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]


In [ ]:
## flatten : it returns a copy of array and collapse into 1d array ##
## if we change elements in copied array it won't effect original array ##

In [80]:
a=np.arange(1,10).reshape(3,3)
print(a)

b=a.flatten()
print(b)

b[0]=0
print(b)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[0 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
## ravel : it returns a view of array and collapse into 1d array ##
## if we change elements in copied array it will effect original array ##

In [82]:
a=np.arange(1,10).reshape(3,3)
print(a)

b=a.ravel()
print(b)

b[0]=0
print(b)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[0 2 3 4 5 6 7 8 9]
[[0 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
## split:it will split the array into parts ##
## axis=0 for rows , axis=1 for columns ##

In [85]:
a=np.arange(1,7).reshape(2,3)
print(a)
print(np.split(a,2))

[[1 2 3]
 [4 5 6]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [88]:
print(np.split(a,3,axis=1))

print(np.split(a,2,axis=0))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [101]:
## concatenate: it will join two arrays shape must be similar ##
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a,b),axis=0))

[[1 2]
 [3 4]
 [5 6]]


In [109]:
## vstack: join sequence vertically (row wise) ## for 2d axis=0

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.vstack((a, b)))

a=np.arange(6).reshape(2,3)
b=np.arange(4,10).reshape(2,3)
print(a)
print(b)
print(np.vstack((a, b)))

[[1 2 3]
 [4 5 6]]
[[0 1 2]
 [3 4 5]]
[[4 5 6]
 [7 8 9]]
[[0 1 2]
 [3 4 5]
 [4 5 6]
 [7 8 9]]


In [110]:
## hstack: join sequence horizontally (col wise) ## for 2d axis=1

a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])
print(np.hstack((a, b)))

a=np.arange(6).reshape(2,3)
b=np.arange(4,10).reshape(2,3)
print(a)
print(b)
print(np.hstack((a, b)))

[[1 2 3 4 5 6]]
[[0 1 2]
 [3 4 5]]
[[4 5 6]
 [7 8 9]]
[[0 1 2 4 5 6]
 [3 4 5 7 8 9]]


In [114]:
## insert : it inserts value at specified position ##
## syntax: np.insert(a,obj,values,axis) obj=index,values=values we are inserting ##

a=np.arange(6).reshape(2,3)
print(a)
print(np.insert(a,3,4))
print(np.insert(a,(1,3),4))

[[0 1 2]
 [3 4 5]]
[0 1 2 4 3 4 5]
[0 4 1 2 4 3 4 5]


In [126]:
## append :it appends values at end ##

a=np.arange(6).reshape(2,3)
print(a)
print(np.append(a,[10,20]))

[[0 1 2]
 [3 4 5]]
[ 0  1  2  3  4  5 10 20]


In [127]:
## delete ##
print(np.delete(a,2))

[0 1 3 4 5]
